### ISSUE TITLE
Can't change bits in "big" number

### ISSUE THREAD

**Issue by nia40m** [nia40m/sublime-display-nums#5]
Trying to change any bit in number `0xffffffffffffffffull` I got python exception trace:
```
Traceback (most recent call last):
  File "/home/nsokolov/.config/sublime-text-3/Packages/Display numbers/display_nums.py", line 341, in select_function
    view.run_command(data.get("func"), data.get("data"))
  File "/opt/sublime_text/Lib/python33/sublime.py", line 1309, in run_command
    sublime_api.view_run_command(self.view_id, cmd, args)
OverflowError: int too big to convert
```

**Comment by nia40m** [comment]
Incidentally fixed this bug with this https://github.com/nia40m/sublime-display-nums/commit/be41d964110f76e99df495f72c1fac1470a920bf.
